# Generated by Django 2.1.5 on 2020-01-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resume_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('template', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_summary', models.CharField(blank=True, max_length=1500, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('mobileno', models.IntegerField(blank=True, null=True)),
                ('Latest_Degree', models.CharField(blank=True, max_length=25, null=True)),
                ('school_name', models.CharField(blank=True, max_length=500, null=True)),
                ('university_name', models.CharField(blank=True, max_length=500, null=True)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('Passout_year', models.IntegerField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('experience', models.IntegerField(blank=True, default=0, null=True)),
                ('summary', models.CharField(blank=True, max_length=1500, null=True)),
                ('skills', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
